// <auto-generated />
namespace ProyectoFinal_HG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ListaVenta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ListaVenta));
        
        string IMigrationMetadata.Id
        {
            get { return "202101091644483_ListaVenta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
