// <auto-generated />
namespace ProyectoFinal_HG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Formula_c : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Formula_c));
        
        string IMigrationMetadata.Id
        {
            get { return "202101092234169_Formula_c"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
